# Generated by Django 3.2.5 on 2021-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210725_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
