# Generated by Django 4.0 on 2022-03-02 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("type", models.CharField(choices=[("Received", "Received"), ("Spent", "Spent")], default="Spent", max_length=100)),
                ("amount", models.FloatField(default=0.0)),
                ("description", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("category", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="expenseTracker.category")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.user")),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
    ]
