# Generated by Django 4.0 on 2022-01-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(max_length=500)),
                ("content", models.TextField()),
                ("published_date", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.user")),
            ],
        ),
    ]
